### ISSUE TITLE
Error in integrating with react template

### ISSUE THREAD

**Issue by sam-the-tutor** [id-daniel-mccoy/ic-auth#1]
I generated a sample react project template using dfx, and after installing the ic-auth package, I am getting this error when i try to import any of the wallets from the package.
![ic-auth](https://github.com/id-daniel-mccoy/ic-auth/assets/102605200/be1873ab-fd95-4798-85f8-471a35673fd5)
Any idea on what is causing this?

**Comment by id-daniel-mccoy** [comment]
Will look into that over the weekend and leave an update here, thanks for letting me know!

**Comment by sam-the-tutor** [comment]
Alright, I will be waiting

**Comment by id-daniel-mccoy** [comment]
My apologies for the extra long wait on this, I did end up hunting down the issue and it turned out to be a t.ds generation issue. It has now been fixed in version 0.9.1

Thank you for your patience and I really apologize for the inconvenience and the wait time.

**Comment by sam-the-tutor** [comment]
I have tested it on my end. It now works well. Thank you for the fix
